# Symfony versions prior to 5.3
security:
    enable_authenticator_manager: true
    
    encoders:   
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:

        login:
            pattern: ^/api/login
            stateless: true
            
            json_login:
                check_path: /api/login
                username_path: email                       
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        register:
            pattern: ^/api/register
            
        api:
            pattern: ^/api
            provider: app_user_provider
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
